"""add full_description to product

Revision ID: 384059528303
Revises: 9b31dd88f336
Create Date: 2025-12-12 16:59:56.728555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384059528303'
down_revision = '9b31dd88f336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_description', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('full_description')

    # ### end Alembic commands ###
